-- drop local objects
USE ROLE SYSADMIN;
DROP DATABASE IF EXISTS HP_DB_PROD;
DROP WAREHOUSE IF EXISTS HP_APP_PROD;

-- create local admin role
USE ROLE SECURITYADMIN;
DROP ROLE IF EXISTS HP_ADM_PROD;
CREATE ROLE HP_ADM_PROD;
GRANT ROLE HP_ADM_PROD TO ROLE SYSADMIN;

-- create local objects
USE ROLE SYSADMIN;
CREATE DATABASE HP_DB_PROD;
CREATE SCHEMA HP_DB_PROD.HP_SCH_PROD;
DROP SCHEMA PUBLIC;
CREATE WAREHOUSE HP_APP_PROD WAREHOUSE_SIZE = XSMALL;

-- transfer ownership to local admin
USE ROLE SECURITYADMIN;
GRANT OWNERSHIP ON DATABASE HP_DB_PROD TO ROLE HP_ADM_PROD;
GRANT OWNERSHIP ON SCHEMA HP_DB_PROD.HP_SCH_PROD TO ROLE HP_ADM_PROD;
GRANT OWNERSHIP ON WAREHOUSE HP_APP_PROD TO ROLE HP_ADM_PROD;

-- create local database roles
USE ROLE HP_ADM_PROD;
CREATE DATABASE ROLE HP_APP_PROD;
CREATE DATABASE ROLE HP_RW_PROD;
CREATE DATABASE ROLE HP_RO_PROD;
 
-- create the hierarchy of database roles
GRANT DATABASE ROLE HP_RO_PROD TO DATABASE ROLE HP_RW_PROD;
GRANT DATABASE ROLE HP_RO_PROD TO DATABASE ROLE HP_APP_PROD;
GRANT DATABASE ROLE HP_APP_PROD TO ROLE HP_ADM_PROD;

-- grant privileges on local databaae roles
GRANT USAGE ON DATABASE HP_DB_PROD TO DATABASE ROLE HP_RW_PROD;
GRANT USAGE ON DATABASE HP_DB_PROD TO DATABASE ROLE HP_RO_PROD;
 
GRANT USAGE ON SCHEMA HP_DB_PROD.HP_SCH_PROD TO DATABASE ROLE HP_RO_PROD;
GRANT USAGE ON SCHEMA HP_DB_PROD.HP_SCH_PROD TO DATABASE ROLE HP_RW_PROD;
